convo/chat/urls.py
from django.urls import path
from django.conf.urls import url

from .consumers import ChatConsumer
from . import views

app_name = 'chat'
urlpatterns = [
    path("", views.chats, name="chats"),
    path("<str:other_username>", views.chat, name="chat"),
]

websocket_urlpatterns = [
    url(r"^chat/(?P<other_username>[\w.@+-]+)$", ChatConsumer.as_asgi() )
]

convo/convo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('chat/', include('chat.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

convo/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path("", views.index, name="index"),

    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    path("search", views.search, name="search"),
    path("friends", views.friends, name="friends"),
    path("requests", views.requests, name="requests"),
    path("profile/<str:name>", views.profile, name="profile"),
    path("notifications", views.notifications, name="notifications"),
]

convo/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    pass


class Request(models.Model):
    requester = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name="requester") # contains who has requested
    requestee = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name="requestee") # contains who has a request
    seen      = models.BooleanField(default=False)


class Friend(models.Model):
    user1       = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user1")
    user2       = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user2")


GENDER_CHOICES = (
    ('Prefer not to say','Prefer not to say'),
    ('Female', 'Female'),
    ('Male','Male'),
    ('Other','Other'),
)

class Profile(models.Model):
    name    = models.TextField(default='Unknown')
    user    = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    image   = models.ImageField(default='default_user.png', blank=True)
    bio     =  models.TextField(null=True, blank=True)
    gender  = models.CharField(max_length=20, null=True, blank=True, choices=GENDER_CHOICES, default=None)
    address = models.TextField(null=True, blank=True)

convo/users/forms.py
from django import forms
from .models import Profile

class EditProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'bio', 'gender', 'address']

convo/users/views.py
import json
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from itertools import chain
from django.utils import timezone

from .models import User, Request, Friend, Profile
from chat.models import Thread
from .forms import EditProfile
from .utils import get_button, post_button_data, save_form_data


# Create your views here.
def index(request):
    return render(request, "users/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("chat:chats"))
        else:
            return render(request, "users/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "../templates/users/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("users:index"))


def register(request):
    if request.method == "POST":
        name = request.POST["name"]
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "users/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
            Profile.objects.create(user=user, name=name)
        except IntegrityError:
            return render(request, "users/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("chat:chats"))
    else:
        return render(request, "users/register.html")


def search(request):
    query = request.GET.get("q")

    if query:
        users = User.objects.filter(username__icontains=query)
        profiles = Profile.objects.filter(user__in=users)

        page_number = request.GET.get('page', 1)
        paginated_profiles = Paginator(profiles, 15).get_page(page_number)
        msg = "Searched for " + query

        return render(request, "users/profile_list.html", {
            "msg": msg,
            "paginated_profiles": paginated_profiles
        })

    else:
        return HttpResponseRedirect(reverse("chat:chats"))


@login_required(login_url="users:login")
def friends(request):
    user = request.user
    friends = chain(Friend.objects.filter(user2=user).values('user1'), Friend.objects.filter(user1=user).values('user2'))

    profiles = []
    for friend in friends:
        user_in = friend.get('user1') if friend.get('user1') is not None else friend.get('user2')
        profile = Profile.objects.get(user__id=user_in)
        profiles.append(profile)

    page_number = request.GET.get('page', 1)
    paginated_profiles = Paginator(profiles, 15).get_page(page_number)
    msg = "Start a chat!"

    return render(request, "users/profile_list.html", {
        "msg": msg,
        "paginated_profiles": paginated_profiles
    })


@login_required(login_url="users:login")
def requests(request):
    user = request.user
    chat_requests = Request.objects.filter(requestee=user)

    profiles = []
    for chat_request in chat_requests:
        chat_request.seen = True
        chat_request.save()
        profile = Profile.objects.get(user=chat_request.requester)
        profiles.append(profile)

    page_number = request.GET.get('page', 1)
    paginated_profiles = Paginator(profiles, 15).get_page(page_number)
    msg = "Chat requests"

    return render(request, "users/profile_list.html", {
        "msg": msg,
        "paginated_profiles": paginated_profiles
    })


@login_required(login_url="users:login")
@csrf_exempt
def profile(request, name):
    user = request.user
    other_user = User.objects.get(username=name)
    profile = Profile.objects.get(user=other_user)

    button = None
    form = None

    if request.method == "GET":
        if user != other_user:
            button = get_button(user, other_user)
        else:
            form = EditProfile()

    if request.method == "POST":
        try:
            button = json.loads(request.body).get('button')
            button = post_button_data(user, other_user, button)
            return JsonResponse({"button": button})

        except:
            save_form_data(request, profile)
            form = EditProfile()


    return render(request, "users/profile.html", {
        "other_user": other_user,
        "profile": profile,
        "button": button,
        "form": form
    })


@login_required(login_url="users:login")
def notifications(request):
    user = request.user
    new_req = 'false'
    new_msg = 'false'

    requests = Request.objects.filter(requestee=user)
    for request in requests:
        if request.seen == False:
            new_req = 'true'
            break
    
    users_with_new_msg = chain(Thread.objects.filter(user2=user).values('new_msg_for'), Thread.objects.filter(user1=user).values('new_msg_for'))
    for user_with_new_msg in users_with_new_msg:
        if user_with_new_msg['new_msg_for'] == user.id:
            new_msg = 'true'
            break

    return JsonResponse({"new_req": new_req, "new_msg": new_msg})

convo/users/templates/users/index.html
{% extends "layout.html" %}

{% block body %}
    <div class="card">
        <div class="card-header">
            <h1>Convo</h1>
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p>This is a django chat application integrated with the freedom of chatting either by text or voice as per each of the user's convenience</p>
            <footer class="blockquote-footer">
                {% if not user.is_authenticated %}
                    <p><a href="{% url 'users:register' %}">Join</a> now if you haven't already.</p>
                    <p>Or simply just <a href="{% url 'users:login' %}">log in</a> and strike up a conversation!</p>
                {% endif %}
            </footer>
          </blockquote>
        </div>
      </div>
{% endblock %}

convo/users/templates/users/login.html
{% extends "layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <hr>

    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">@</span>
            </div>
            <input type="text" name="username" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
          </div>
        <div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"></span>
            </div>
            <input type="password" name="password" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1">
            </div>
        <input class="btn btn-secondary" type="submit" value="Login">
    </form>

    <hr>
    <p>Don't have an account? <a href="{% url 'users:register' %}">Register here.</a>
    </p>
{% endblock %}

convo/users/templates/users/profile.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
    <h1>Profile</h1>
    <div>
        <img src="{{ profile.image.url }}" style="width:50%;"/>
    </div>
    <h5 class="p-2" id="name">{{ profile.name }}</h5>
    <br><br>
    <div>
        <h4><b>Username:</b></h4><p id="username">{{ profile.user.username }}</p>
        {% if profile.bio is not None %}
            <h4><b>Bio:</b></h4> <div id="profile-bio">{{ profile.bio }}</div>
        {% endif %}
        <br>
        {% if profile.gender is not None %}
            <h4><b>Gender:</b></h4> <div id="profile-gender">{{ profile.gender }}</div>
        {% endif %}
        <br>
        {% if profile.address is not None %}
        <h4><b>Address:</b></h4> <div id="profile-address">{{ profile.address }}</div>
        {% endif %}

        {% if other_user == user %}
        <br>
            <form class="text-light bg-secondary" style="display: none; max-width: 50%;" id="profile-form" action="{% url 'users:profile' other_user %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>Image: </p>{{ form.image }}
                <hr>
                <p>Gender: </p>{{ form.gender }}
                <hr>
                <p>Bio: </p>{{ form.bio }}
                <hr>
                <p>Address: </p>{{ form.address }}
                <br>
                <input class="btn btn-dark" type="submit" value="Update">
            </form>
            <br>
            <div class="btn btn-dark" id="edit" onclick="profileEdit()" class="text-primary">Edit</div>
        {% else %}
            <br>
            <div id="btn-div">
                {% csrf_token %}
                    <input type="button" id="btn" class="btn btn-secondary" name="button" onclick="postButton('btn')" value="{{ button }}">
                {% if button == 'Accept' %}
                    <input type="button" id="btn2" class="btn btn-secondary" name="button2" onclick="postButton('btn2')" value="Reject">
                {% elif button == 'Unfriend' %}
                    <a id="chat-btn" class="btn btn-secondary mr-sm-2" href="{% url 'chat:chat' other_user.username %}">
                        Chat
                    </a>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block script %}
    <script src="{% static './profile.js' %}"></script>
{% endblock %}

convo/users/templates/users/profile_list.html
{% extends "layout.html" %}

{% block body %}

    <h2>{{ msg }}</h2>

    {% if paginated_profiles.has_previous %}
        <a href="?page={{ paginated_profiles.previous_page_number }}">previous</a>
    {% endif %}

    {% for profile in paginated_profiles %}
        <a href="{% url 'users:profile' profile.user %}">
            <div class="card mt-5 mr-auto ml-auto rounded" style="width: 50rem;">
                {% if profile.image is not None %}
                    <img class="card-img-top" src="{{ profile.image.url }}"/>
                {% endif %}
                <div class="card-body">
                    <p class="card-text">{{ profile.user }}</p>
                    {% if profile.address is not None %}
                        <p class="card-text">{{ profile.address }}</p>
                    {% endif %}
                </div>
            </div>
        </a>
    {% empty %}
        <h5 class="m-auto p-5">None</h5>
    {% endfor %}

    {% if paginated_profiles.has_next %}
    <a href="?page={{ paginated_profiles.next_page_number }}">next</a>
    {% endif %}

{% endblock %}

convo/users/templates/users/register.html
{% extends "layout.html" %}
{% load static %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <hr>

    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"></span>
          </div>
          <input type="text" name="name" class="form-control" placeholder="Name" aria-label="Name" aria-describedby="basic-addon1">
      </div>
      <div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">@</span>
            </div>
            <input type="text" name="username" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1"></span>
            </div>
            <input type="email" name="email" class="form-control" placeholder="Email Address" aria-label="Email Address" aria-describedby="basic-addon1">
        </div>
        <div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1"></span>
            </div>
            <input type="password" name="password" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1">
        </div>
        <div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1"></span>
                </div>
                <input type="password" name="confirmation" class="form-control" placeholder="Confirm Password" aria-label="Confirm Password" aria-describedby="basic-addon1">
            </div>
        <div>
        <input class="btn btn-secondary" type="submit" value="Register">
    </form>

    <hr>
    Already have an account? <a href="{% url 'users:login' %}">Log In here.</a>
{% endblock %}

{% block script %}
    <script src="{% static './register.js' %}"></script>
{% endblock %}